### Objectives
1. Introduction and concepts
2. Properties of PCA
3. Applications of PCA
</hr>

### Introduction
1. Main idea is to reduce the Dimensionality of the data 
2. Dimensions of the data means columns in data
3. Feature selection means choosing the important feature
4. Dimensionality reduction is about deriving the new features(m) out of original features (n)
5. m<n
6. We don't want to compromise on the Acuuracy.
7. this is achieved by transforming the varibles(columns) to a new set of variables (columns) which are known as principle components
8. This principle components have a parameter telling how important they are in representing the data.

In [3]:
from sklearn.decomposition import PCA

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
from sklearn.datasets import load_breast_cancer

In [5]:
breast_cancer = load_breast_cancer()

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
mm = MinMaxScaler()

In [9]:
data = mm.fit_transform(breast_cancer.data)

In [10]:
data.shape

(569, 30)

In [11]:
pca = PCA(n_components= 10)

In [12]:
pca.fit_transform(data)

array([[ 1.38702121,  0.42689533, -0.54170264, ..., -0.03945614,
         0.07759016,  0.15529593],
       [ 0.46230825, -0.55694674, -0.20517458, ...,  0.02064416,
        -0.07064091, -0.08528252],
       [ 0.95462147, -0.10970115, -0.1478484 , ...,  0.00736163,
        -0.05933887, -0.07368308],
       ...,
       [ 0.22631131, -0.28794577,  0.31522402, ...,  0.01570685,
        -0.10832731, -0.07691735],
       [ 1.67783369,  0.33594595,  0.29611601, ..., -0.09247414,
         0.08378366,  0.00544931],
       [-0.90506804, -0.10410875,  0.38285993, ...,  0.03943233,
        -0.01987828,  0.10547828]])

In [13]:
pca.explained_variance_

array([0.33133389, 0.10785038, 0.0443947 , 0.04000678, 0.02549742,
       0.01916637, 0.00986455, 0.00743488, 0.00616788, 0.00589966])

### Notes
1. Scaling should be done before PCA
2. Explained_varience tells how important those derived features are.

In [16]:
pca.components_.shape

(10, 30)

In [17]:
import pandas as pd

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [21]:
df = pd.DataFrame({'A':[1,2,3,4,5],'B':[2,3,4,5,6]})

In [22]:
pca =PCA(n_components= 1)

In [23]:
pca.fit_transform(df)

array([[ 2.82842712],
       [ 1.41421356],
       [-0.        ],
       [-1.41421356],
       [-2.82842712]])

In [24]:
pca.components_

array([[-0.70710678, -0.70710678]])