# FEATURE SELECTION TECHNIQUES

### Agenda

1. Feature selection vs Feature engineering vs dimensionality reduction
2. Feature selection methods
3. Filter methods 
4. Wrappper methods
5. Hybrid method
6. Advaced methods

### * Feature selection vs feature engineering vs dimensionality reduction

1. Feature Selection : It is a process to reduce the columns that is considered in the machine learning
    Benefits : Shorter training time, reduce overfitting, model can be more intrepretable
2. Feature engineering : This is all about the preprocessing te,mchnique to make the model effective, Ex : one hot encoder, ordinal encooder
    Benefits : Improved model accuracy
3. Dimensionality Reduction : techniques like PCA, SVD i,e which transforms the high dimension of the data into low dimension such that memory is low
    Benefits : improves the accuracy, Shorter  training time

### 2. Feature selection models
1. Filter models : Simple way  of choosing the  columns which we think useless and columns which we think that it impacts the target column
   without any ml algorithm
2. Wrapper models : the feature selection is done by using the ml algorithm. Which is a best feature predictor
3. Embedded models


Filter Methods for Feature Selection
Feature selection method idenpendently of ML algo.
Based on characterstics of data.
These are simple & quick way of feature selection
Advantages
Selected features can be used for all ML algorithms. This means if you change ML algo, no need to change the feature selected.
Computationally not so expensive.

### types 
1. Univariate Filter Based Methods - These methods treat each feature idependently
2. Multivariate Filter based Methods - They will use relationship between features.

In [2]:
from sklearn.feature_selection import VarianceThreshold
ve = VarianceThreshold(threshold= 0.2)

In [6]:
from sklearn.preprocessing import OrdinalEncoder
df['A'] = OrdinalEncoder().fit_transform(df[['A']])

In [5]:
import pandas as pd
df = pd.DataFrame({'A':['m','f','m','m','m','m','m','m'], 
              'B':[1,2,3,1,2,1,1,1], 
              'C':[1,2,3,1,2,1,1,1]})


C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [8]:
ve.fit_transform(df)

array([[1., 1.],
       [2., 2.],
       [3., 3.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
ve.variances_

array([0.109375, 0.5     , 0.5     ])

### Correlation  Factor

1. Correlation is measured as the linear realtionship between the two quantitative features(i.e continuos in nature). It tells the how one variable is dependent on the another varibale i,e target variable
2. Say if we have 3 features and we have to find the important features for model predicting. lets say we have A,B,C and target column as T
    we have to find the correlation between the  A &T, B&T, C&T.
3. If we see the A & B are corelated and what we have tto do?
4. Since A and B provides the redudent information to model prediction T, thus one them has to be removed.

In [16]:
pd.DataFrame({'a' : [1,2,3,4,5], 'b':[2,3,4,5,6]})

a  b
0  1  2
1  2  3
2  3  4
3  4  5
4  5  6

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/winequality-white.csv', sep=';')

In [21]:
corr = df.corr(method = 'pearson')

In [22]:
corr.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, fixed acidity to quality
Data columns (total 12 columns):
fixed acidity           12 non-null float64
volatile acidity        12 non-null float64
citric acid             12 non-null float64
residual sugar          12 non-null float64
chlorides               12 non-null float64
free sulfur dioxide     12 non-null float64
total sulfur dioxide    12 non-null float64
density                 12 non-null float64
pH                      12 non-null float64
sulphates               12 non-null float64
alcohol                 12 non-null float64
quality                 12 non-null float64
dtypes: float64(12)
memory usage: 1.2+ KB


In [25]:
import numpy as np

In [26]:
np.abs(corr.loc['fixed acidity']).sort_values(ascending = False)[:5]

fixed acidity    1.000000
pH               0.425858
citric acid      0.289181
density          0.265331
alcohol          0.120881
Name: fixed acidity, dtype: float64

### Chi-Squared method

1. Used for testing relationship between the categorical values(binary targets/ counts)
2. Calculated the realtionship between  all the features and target which both are catogrical in nature

In [27]:
from sklearn.feature_selection import chi2, SelectKBest

In [28]:

cols = ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship'
        ,'race','sex','capital-gain','capital-loss','hours-per-week','native-country','Salary']
adult_data = pd.read_csv('https://raw.githubusercontent.com/zekelabs/data-science-complete-tutorial/master/Data/adult.data.txt', names=cols)

In [36]:
cat_col = adult_data.select_dtypes(include = ['object'])

In [30]:
oe = OrdinalEncoder()


In [37]:
data_td = oe.fit_transform(cat_col)

In [44]:
df = pd.DataFrame(data_td, columns = list(cat_col.columns))
df

workclass  education  marital-status  occupation  relationship  race  \
0            7.0        9.0             4.0         1.0           1.0   4.0   
1            6.0        9.0             2.0         4.0           0.0   4.0   
2            4.0       11.0             0.0         6.0           1.0   4.0   
3            4.0        1.0             2.0         6.0           0.0   2.0   
4            4.0        9.0             2.0        10.0           5.0   2.0   
...          ...        ...             ...         ...           ...   ...   
32556        4.0        7.0             2.0        13.0           5.0   4.0   
32557        4.0       11.0             2.0         7.0           0.0   4.0   
32558        4.0       11.0             6.0         1.0           4.0   4.0   
32559        4.0       11.0             4.0         1.0           3.0   4.0   
32560        5.0       11.0             2.0         4.0           5.0   4.0   

       sex  native-country  Salary  
0      1.0            39.0     0.0  
1      1.0            39.0     0.0  
2      1.0            39.0     0.0  
3      1.0            39.0     0.0  
4      0.0             5.0     0.0  
...    ...             ...     ...  
32556  0.0            39.0     0.0  
32557  1.0            39.0     1.0  
32558  0.0            39.0     0.0  
32559  1.0            39.0     0.0  
32560  0.0            39.0     1.0  

[32561 rows x 9 columns]

In [65]:
chi, pval = chi2(df.drop(columns = ['Salary']), df.Salary)
chi

array([  47.50811916,  297.94227041, 1123.46981798,  504.5588538 ,
       3659.14312486,   33.03130514,  502.43941948,   13.61925602])

In [63]:
index = list(df.drop(columns =['Salary']).columns)


In [ ]:
feature_importances = pd.Series(chi_2, index=list(df.drop(columns=['Salary']).columns.values))

In [68]:
feature_importances = pd.Series(chi, index =index )
feature_importances.sort_values(ascending = False)[:4]

relationship      3659.143125
marital-status    1123.469818
occupation         504.558854
sex                502.439419
dtype: float64

In [75]:
se   = SelectKBest(k= 4, score_func = chi2)

In [76]:
se.fit_transform(df.drop(columns = ['Salary']), df.Salary)

array([[4., 1., 1., 1.],
       [2., 4., 0., 1.],
       [0., 6., 1., 1.],
       ...,
       [6., 1., 4., 0.],
       [4., 1., 3., 1.],
       [2., 4., 5., 0.]])

In [77]:
se.scores_

array([  47.50811916,  297.94227041, 1123.46981798,  504.5588538 ,
       3659.14312486,   33.03130514,  502.43941948,   13.61925602])

Conclusion :
    PS: Correlation is finding the relationship between the continuos data which both the feature and target data should be continuos
        Chi2 method is used for finding the relationship between the catogrical features and  catgorical target

ANOVA univariate TEST:
    1. Suited if the feature is continuos and normally distributed
    2. Target column can be continous f_classif
    3. Target column can be catogrical f_regression


In [78]:
wine_data = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/winequality-white.csv', sep=';')

In [87]:
feature_data = wine_data.drop(columns= ['quality'])

In [80]:
from sklearn.feature_selection import f_classif

In [82]:
ss = SelectKBest(k = 8, score_func= f_classif)

In [89]:
feature_data = ss.fit_transform(feature_data, wine_data.quality)

In [95]:
from sklearn.model_selection import train_test_split

In [97]:
trainX, testX, trainY, testY = train_test_split(feature_data, wine_data.quality)

In [93]:
from sklearn.linear_model import LogisticRegression

In [94]:
le = LogisticRegression()

In [98]:
le.fit(trainX, trainY)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [99]:
testX1 = le.predict(testX)

In [101]:
from  sklearn.metrics import accuracy_score

In [102]:
accuracy_score(testX1, testY)

0.529795918367347

In [103]:
from sklearn.tree import DecisionTreeClassifier
de = DecisionTreeClassifier()

In [104]:
de.fit(trainX, trainY)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [105]:
testX2 = de.predict(testX)

In [106]:
accuracy_score(testX2, testY)

0.5853061224489796

Wrapper methods :
    1. This is type of feature selection method in which the feature_data is divided into subcolumns or subdata and predicting the accuracy of the model
    2. This uses the ML algo and works under the ML algo
    3. If the ML algo is changed the Feature_data should also be changed

### Wrapper methods
1. Using the iterative methods we can find the best subset of features by ML algo for giving the best accuracy
2. This process is dependent on ML algo
3. Whenever we change the algo the selected features also change

#### Advantages 
1. It does the feature selection based on the Best accuracy
2. It also accounts for the interactions among the features

#### Process of applying the Wrapper methods
1. <b> Search</b> for the subset of features
2. <b> Built </b> model using subset
3. <b> evaluate </b> trained the model using the choosen matrix
4. <b> iterate </b>  repeat the process untill you success

#### Searching for the subset of features
1. Start small start with one feature and keep on addding the one. Stop the model where your acuuracy gets improved
2. Start with all features and try to remove it one by one
3. Randamize and try the possible combinations

In [15]:
def f(r):
    if r<=3:
        return 1
    elif r<=6:
        return 2
    else:
        return 3
df['quality'] = df.quality.map(f)

In [17]:
features =  list(df.columns)

features.remove('quality')
features

['fixed acidity',
 'volatile acidity',
 'citric acid',
 'residual sugar',
 'chlorides',
 'free sulfur dioxide',
 'total sulfur dioxide',
 'density',
 'pH',
 'sulphates',
 'alcohol']

In [21]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    45.0                 170.0  1.00100  3.00       0.45   
1                    14.0                 132.0  0.99400  3.30       0.49   
2                    30.0                  97.0  0.99510  3.26       0.44   
3                    47.0                 186.0  0.99560  3.19       0.40   
4                    47.0                 186.0  0.99560  3.19       0.40   
...                   ...                   ...      ...   ...        ...   
4893                 24.0                  92.0  0.99114  3.27       0.50   
4894                 57.0                 168.0  0.99490  3.15       0.46   
4895                 30.0                 111.0  0.99254  2.99       0.46   
4896                 20.0                 110.0  0.98869  3.34       0.38   
4897                 22.0                  98.0  0.98941  3.26       0.32   

      alcohol  quality  
0         8.8        2  
1         9.5        2  
2        10.1        2  
3         9.9        2  
4         9.9        2  
...       ...      ...  
4893     11.2        2  
4894      9.6        2  
4895      9.4        2  
4896     12.8        3  
4897     11.8        2  

[4898 rows x 12 columns]

In [22]:
try_data = []
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

for value in features:
    try_data.append(value)
    
    trainX, testX, trainY, testY = train_test_split(df[try_data], df.quality)
    de = DecisionTreeClassifier()
    de.fit(trainX, trainY)
    print(de.score(testX, testY), try_data)

0.7755102040816326 ['fixed acidity']
0.7502040816326531 ['fixed acidity', 'volatile acidity']
0.756734693877551 ['fixed acidity', 'volatile acidity', 'citric acid']
0.7820408163265307 ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar']
0.7665306122448979 ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides']
0.8016326530612244 ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide']
0.8106122448979591 ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide']
0.8171428571428572 ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density']
0.8204081632653061 ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH']
0.8122448979591836 ['fixed acidity', '

In [33]:
from mlxtend.feature_selection import SequentialFeatureSelector
sts = SequentialFeatureSelector(k_features= 5, estimator=DecisionTreeClassifier())

In [34]:
sts.fit(trainX, trainY)

SequentialFeatureSelector(clone_estimator=True, cv=5,
                          estimator=DecisionTreeClassifier(class_weight=None,
                                                           criterion='gini',
                                                           max_depth=None,
                                                           max_features=None,
                                                           max_leaf_nodes=None,
                                                           min_impurity_decrease=0.0,
                                                           min_impurity_split=None,
                                                           min_samples_leaf=1,
                                                           min_samples_split=2,
                                                           min_weight_fraction_leaf=0.0,
                                                           presort=False,
                                                           random_

In [43]:
sts.k_feature_names_

('fixed acidity', 'citric acid', 'residual sugar', 'sulphates', 'alcohol')

In [44]:
for i in range(4, 10):
    sts = SequentialFeatureSelector(k_features= 5, estimator= DecisionTreeClassifier())
    sts.fit(trainX, trainY)
    print(sts.k_score_, i)

0.8050572152462623 4
0.8056110848159183 5
0.8050579576987683 6
0.8050594426037808 7
0.8075039674805803 8
0.8023442937884567 9


In [41]:
sts.k_score_

0.8064199868214681

In [ ]:
from mlxtend.feature_selection import ExhaustiveFeatureSelector
ex = ExhaustiveFeatureSelector(estimator= DecisionTreeClassifier(), min_features=3, max_features=10)
ex.fit(trainX, trainY)
print(ex.best_score_)

In [ ]:
ex.