## About the data

### Predict Loan Eligibility for Dream Housing Finance company
Dream Housing Finance company deals in all kinds of home loans. They have presence across all urban, semi urban and rural areas. Customer first applies for home loan and after that company validates the customer eligibility for loan.

Company wants to automate the loan eligibility process (real time) based on customer detail provided while filling online application form. These details are Gender, Marital Status, Education, Number of Dependents, Income, Loan Amount, Credit History and others. To automate this process, they have provided a dataset to identify the customers segments that are eligible for loan amount so that they can specifically target these customers. 



In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
%matplotlib inline
import missingno as mg

In [2]:
train = pd.read_csv('loan_train.csv')

In [55]:
test = pd.read_csv('loan_test.csv')

In [3]:
data = train.copy()

In [4]:
data1 = train.Gender.copy()

In [5]:
data.drop(columns = ['Loan_ID'], inplace = True)

In [56]:
test.drop(columns = ['Loan_ID'], inplace = True)

In [6]:
data.fillna(0, inplace = True)

In [7]:
data['Gender'] = train.Gender.map({'Male' : 1, 'Female': 0})

In [57]:
test['Gender'] = test.Gender.map({'Male' : 1, 'Female': 0})

In [ ]:
data['Married'] =data['Married'].map({'No': 0, 'Yes': 1})

In [58]:
test['Married'] =test['Married'].map({'No': 0, 'Yes': 1})

In [9]:
data['Dependents'] = data['Dependents'].map({'0': 0, '1': 1, '2': 2, '3+': 3})

In [59]:
test['Dependents'] = test['Dependents'].map({'0': 0, '1': 1, '2': 2, '3+': 3})

In [10]:
data.sample(1)

Gender  Married  Dependents Education Self_Employed  ApplicantIncome  \
195     1.0      1.0         1.0  Graduate            No             3125   

     CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
195             2583.0       170.0             360.0             1.0   

    Property_Area Loan_Status  
195     Semiurban           N

In [11]:
data['Education'] = data['Education'].map({'Graduate': 1, 'Not Graduate': 0})

In [60]:
test['Education'] = test['Education'].map({'Graduate': 1, 'Not Graduate': 0})

In [12]:
data['Self_Employed'] = data['Self_Employed'].map({'Yes': 1, 'No':0})

In [61]:
test['Self_Employed'] = test['Self_Employed'].map({'Yes': 1, 'No':0})

In [13]:
data['Loan_Status'] = data['Loan_Status'].map({'Y':1, 'N':0})

In [14]:
data['Property_Area'].unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [15]:
data['Property_Area'] = train['Property_Area'].map({'Urban': 0, 'Rural': 1, 'Semiurban': 2})

In [63]:
test['Property_Area'] = test['Property_Area'].map({'Urban': 0, 'Rural': 1, 'Semiurban': 2})

In [17]:
data.fillna(0, inplace =  True)

In [64]:
test.fillna(0, inplace= True)

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 12 columns):
Gender               614 non-null float64
Married              614 non-null float64
Dependents           614 non-null float64
Education            614 non-null int64
Self_Employed        614 non-null float64
ApplicantIncome      614 non-null int64
CoapplicantIncome    614 non-null float64
LoanAmount           614 non-null float64
Loan_Amount_Term     614 non-null float64
Credit_History       614 non-null float64
Property_Area        614 non-null int64
Loan_Status          614 non-null int64
dtypes: float64(8), int64(4)
memory usage: 57.7 KB


In [19]:
Feature_data = data.drop(columns = ['Loan_Status'])

In [20]:
Target_data = data.Loan_Status

In [21]:
from sklearn.model_selection import train_test_split

In [29]:
trainX, testX, trainY, testY = train_test_split(Feature_data, Target_data)

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
le = LogisticRegression()

In [30]:
le.fit(trainX, trainY)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
pred = le.predict(testX)

In [32]:
from sklearn.metrics import f1_score, accuracy_score

In [33]:
f1_score(testY, pred)

0.859504132231405

In [34]:
accuracy_score(pred, testY)

0.7792207792207793

In [35]:
from sklearn.metrics import confusion_matrix

In [36]:
confusion_matrix(y_pred=  pred, y_true= testY)

array([[ 16,  26],
       [  8, 104]], dtype=int64)

In [37]:
from sklearn.tree import DecisionTreeClassifier

In [38]:
de = DecisionTreeClassifier()

In [39]:
de.fit(trainX, trainY)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [40]:
de_pred = de.predict(testX)

In [41]:
accuracy_score(de_pred, testY)

0.6753246753246753

In [42]:
confusion_matrix(y_pred= de_pred, y_true= testY)

array([[13, 29],
       [21, 91]], dtype=int64)

In [43]:
Yfrom xgboost.sklearn import XGBClassifier

In [44]:
xe = XGBClassifier()

In [45]:
xe.fit(trainX, trainY)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [46]:
xe_pred = xe.predict(testX)

In [47]:
confusion_matrix(y_pred=xe_pred, y_true= testY)

array([[16, 26],
       [17, 95]], dtype=int64)

In [48]:
accuracy_score(xe_pred, testY)

0.7207792207792207

In [49]:
from sklearn.naive_bayes import GaussianNB, Ba

In [50]:
ge = GaussianNB()

In [51]:
ge.fit(trainX, trainY)

GaussianNB(priors=None, var_smoothing=1e-09)

In [52]:
ge_pred = ge.predict(testX)

In [53]:
confusion_matrix(y_pred= ge_pred, y_true= testY)

array([[15, 27],
       [15, 97]], dtype=int64)

In [66]:
test1 = pd.read_csv('loan_test.csv', usecols=['Loan_ID'])

In [78]:
pred_data = le.predict(test)

In [79]:
sub_data = pd.DataFrame(pred_data, index= test1['Loan_ID'], columns = ['Loan_Status'])

In [80]:
sub_data['Loan_Status'] = sub_data['Loan_Status'].map({1: 'Y', 0: 'N'})

In [81]:
sub_data = sub_data.to_csv()

In [82]:
file =  open('loan_sub_data.csv', 'w')
file.write(sub_data)
file.close()
